(self.AMP=self.AMP||[]).push({n:"amp-anim",v:"2005050322002",f:(function(AMP,_){
var c,d="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},e;if("function"==typeof Object.setPrototypeOf)e=Object.setPrototypeOf;else{var f;a:{var k={a:!0},l={};try{l.__proto__=k;f=l.a;break a}catch(a){}f=!1}e=f?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var m=e;var n=self.AMP_CONFIG||{},r=("string"==typeof n.cdnProxyRegex?new RegExp(n.cdnProxyRegex):n.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function t(a){if(self.document&&self.document.head&&(!self.location||!r.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}n.cdnUrl||t("runtime-host");n.geoApiUrl||t("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var u,v="Webkit webkit Moz moz ms O o".split(" ");function w(a,b,x){var y;var p=a.style;if(2>b.length||0!=b.lastIndexOf("--",0)){u||(u=Object.create(null));var g=u[b];if(!g){g=b;if(void 0===p[b]){var h=b.charAt(0).toUpperCase()+b.slice(1);b:{for(var q=0;q<v.length;q++){var z=v[q]+h;if(void 0!==p[z]){h=z;break b}}h=""}void 0!==p[h]&&(g=h)}u[b]=g}b=g}if(b){var A=y?x+y:x;(2>b.length?0:0==b.lastIndexOf("--",0))?a.style.setProperty(b,A):a.style[b]=A}}
function B(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};var C=["alt","aria-label","aria-describedby","aria-labelledby"],D=["src","srcset"];function E(a){a=AMP.BaseElement.call(this,a)||this;a.c=null;a.h=!1;return a}var F=AMP.BaseElement;E.prototype=d(F.prototype);E.prototype.constructor=E;if(m)m(E,F);else for(var G in F)if("prototype"!=G)if(Object.defineProperties){var H=Object.getOwnPropertyDescriptor(F,G);H&&Object.defineProperty(E,G,H)}else E[G]=F[G];E.j=F.prototype;c=E.prototype;
c.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};
c.buildCallback=function(){this.c=new Image;this.c.setAttribute("decoding","async");this.propagateAttributes(C,this.c);this.applyFillContent(this.c,!0);var a=this.element,b=this.c;a.hasAttribute("object-fit")&&w(b,"object-fit",a.getAttribute("object-fit"));a.hasAttribute("object-position")&&w(b,"object-position",a.getAttribute("object-position"));"img"==this.element.getAttribute("role")&&(this.element.removeAttribute("role"),this.user().error("AMP-ANIM","Setting role=img on amp-anim elements breaks screen readers. Please just set alt or ARIA attributes, they will be correctly propagated for the underlying <img> element."));
B(this.c,!this.getPlaceholder());this.element.appendChild(this.c)};c.isRelayoutNeeded=function(){return!0};c.layoutCallback=function(){var a=this.c;this.propagateAttributes(D,a,!0);if(!a.hasAttribute("src")&&0=="srcset"in a){var b=a.getAttribute("srcset");b=/\S+/.exec(b);null!=b&&a.setAttribute("src",b[0])}return this.loadPromise(a)};c.firstLayoutCompleted=function(){this.h=!0;I(this)};c.viewportCallback=function(){this.h&&I(this)};
c.unlayoutCallback=function(){this.c.src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";this.c.srcset="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";this.h=!1;return!0};function I(a){var b=a.isInViewport();a.togglePlaceholder(!b);B(a.c,b)}(function(a){a.registerElement("amp-anim",E)})(self.AMP);
})});

//# sourceMappingURL=amp-anim-0.1.js.map
