(self.AMP=self.AMP||[]).push({n:"amp-bodymovin-animation",v:"2005050322002",f:(function(AMP,_){
var aa="function"==typeof Object.create?Object.create:function(a){function c(){}c.prototype=a;return new c},l;if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var m;a:{var ba={a:!0},ca={};try{ca.__proto__=ba;m=ca.a;break a}catch(a){}m=!1}l=m?function(a,c){a.__proto__=c;if(a.__proto__!==c)throw new TypeError(a+" is not extensible");return a}:null}var da=l;function ea(a,c){c=void 0===c?"":c;try{return decodeURIComponent(a)}catch(b){return c}};var fa=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function r(a){var c=Object.create(null);if(!a)return c;for(var b;b=fa.exec(a);){var e=ea(b[1],b[1]),d=b[2]?ea(b[2].replace(/\+/g," "),b[2]):"";c[e]=d}return c};var t="";
function w(){var a=void 0,c=a||self;if(c.__AMP_MODE)var b=c.__AMP_MODE;else{b=c;var e=self.AMP_CONFIG||{},d=r(b.location.originalHash||b.location.hash);e=e.spt;var f=r(b.location.search);t||(t=b.AMP_CONFIG&&b.AMP_CONFIG.v?b.AMP_CONFIG.v:"012005050322002");b={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(d.development)||b.AMP_DEV_MODE),examiner:"2"==d.development,esm:!1,geoOverride:d["amp-geo"],minified:!0,lite:void 0!=f.amp_lite,test:!1,log:d.log,version:"2005050322002",rtvVersion:t,
singlePassType:e};b=c.__AMP_MODE=b}return b};var ha=Object.prototype.toString;function x(a){return"number"===typeof a&&isFinite(a)};var y=self.AMP_CONFIG||{},ia=("string"==typeof y.cdnProxyRegex?new RegExp(y.cdnProxyRegex):y.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function ja(a){if(!self.document||!self.document.head||self.location&&ia.test(self.location.origin))return null;var c=self.document.head.querySelector('meta[name="'+a+'"]');return c&&c.getAttribute("content")||null}
var z={thirdParty:y.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:y.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof y.thirdPartyFrameRegex?new RegExp(y.thirdPartyFrameRegex):y.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:y.cdnUrl||ja("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:ia,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:y.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:y.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:y.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:y.geoApiUrl||ja("amp-geo-api")};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var A=self.__AMP_LOG;function D(){if(!A.user)throw Error("failed to call initLogConstructor");return A.user}function E(){if(A.dev)return A.dev;throw Error("failed to call initLogConstructor");}function F(a,c,b,e,d){D().assert(a,c,b,e,d,void 0,void 0,void 0,void 0,void 0,void 0)};function ka(){var a,c;this.promise=new Promise(function(b,e){a=b;c=e});this.resolve=a;this.reject=c};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var la=Object.prototype.hasOwnProperty;function G(a){return a||{}};function H(a,c){return c.length>a.length?!1:0==a.lastIndexOf(c,0)};function I(){var a=100;this.G=a;this.m=this.A=0;this.j=Object.create(null)}I.prototype.has=function(a){return!!this.j[a]};I.prototype.get=function(a){var c=this.j[a];if(c)return c.access=++this.m,c.payload};I.prototype.put=function(a,c){this.has(a)||this.A++;this.j[a]={payload:c,access:this.m};if(!(this.A<=this.G)){E().warn("lru-cache","Trimming LRU cache");a=this.j;var b=this.m+1,e;for(e in a){var d=a[e].access;if(d<b){b=d;var f=e}}void 0!==f&&(delete a[f],this.A--)}};G({c:!0,v:!0,a:!0,ad:!0,action:!0});var J,ma;
function K(a){var c;J||(J=self.document.createElement("a"),ma=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new I));var b=c?null:ma,e=J;if(b&&b.has(a))a=b.get(a);else{e.href=a;e.protocol||(e.href=e.href);var d={href:e.href,protocol:e.protocol,host:e.host,hostname:e.hostname,port:"0"==e.port?"":e.port,pathname:e.pathname,search:e.search,hash:e.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;
d.origin=e.origin&&"null"!=e.origin?e.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a}
function L(a,c){var b=void 0===b?"source":b;F(null!=a,"%s %s must be available",c,b);var e=a;a=e;"string"==typeof a&&(a=K(a));var d;(d="https:"==a.protocol||"localhost"==a.hostname||"127.0.0.1"==a.hostname)||(a=a.hostname,d=a.length-10,d=0<=d&&a.indexOf(".localhost",d)==d);F(d||/^(\/\/)/.test(e),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',c,b,e);return e};function na(a,c){var b=oa(a);return!!b[c]}
function oa(a){if(a.__AMP__EXPERIMENT_TOGGLES)return a.__AMP__EXPERIMENT_TOGGLES;a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);var c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var b in a.AMP_CONFIG){var e=a.AMP_CONFIG[b];"number"===typeof e&&0<=e&&1>=e&&(c[b]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length){var d=a.AMP_CONFIG["allow-doc-opt-in"],f=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]');if(f){var g=
f.getAttribute("content").split(",");for(b=0;b<g.length;b++)-1!=d.indexOf(g[b])&&(c[g[b]]=!0)}}Object.assign(c,pa(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){b=a.AMP_CONFIG["allow-url-opt-in"];a=r(a.location.originalHash||a.location.hash);for(var h=0;h<b.length;h++){var n=a["e-"+b[h]];"1"==n&&(c[b[h]]=!0);"0"==n&&(c[b[h]]=!1)}}return c}
function pa(a){var c="";try{"localStorage"in a&&(c=a.localStorage.getItem("amp-experiment-toggles"))}catch(d){E().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var b=c?c.split(/\s*,\s*/g):[];a=Object.create(null);for(var e=0;e<b.length;e++)0!=b[e].length&&("-"==b[e][0]?a[b[e].substr(1)]=!1:a[b[e]]=!0);return a};var qa={},M=(qa["ampdoc-fie"]={isTrafficEligible:function(){return!0},branches:[["21065001"],["21065002"]]},qa);function ra(a){var c=a.ownerDocument.defaultView,b=c.__AMP_TOP||(c.__AMP_TOP=c),e=c!=b;var d=b;if(na(d,"ampdoc-fie")){d.__AMP_EXPERIMENT_BRANCHES=d.__AMP_EXPERIMENT_BRANCHES||{};for(var f in M)if(la.call(M,f)&&!la.call(d.__AMP_EXPERIMENT_BRANCHES,f))if(M[f].isTrafficEligible&&M[f].isTrafficEligible(d)){if(!d.__AMP_EXPERIMENT_BRANCHES[f]&&na(d,f)){var g=M[f].branches;d.__AMP_EXPERIMENT_BRANCHES[f]=g[Math.floor(Math.random()*g.length)]||null}}else d.__AMP_EXPERIMENT_BRANCHES[f]=null;d="21065002"===
(d.__AMP_EXPERIMENT_BRANCHES?d.__AMP_EXPERIMENT_BRANCHES["ampdoc-fie"]:null)}else d=!1;var h=d;e&&!h?a=N(c,"url-replace")?P(c,"url-replace"):null:(a=Q(a),a=sa(a),a=N(a,"url-replace")?P(a,"url-replace"):null);return a}function R(a,c){a=a.__AMP_TOP||(a.__AMP_TOP=a);return P(a,c)}function ta(a,c){var b=Q(a);b=sa(b);return P(b,c)}function Q(a){return a.nodeType?R((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function sa(a){a=Q(a);return a.isSingleDoc()?a.win:a}
function P(a,c){N(a,c);var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});var e=b;a=e[c];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function N(a,c){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[c];return!(!a||!a.ctor&&!a.obj)};function ua(a,c){var b={},e=void 0===b.expr?".":b.expr,d=void 0===b.urlReplacement?0:b.urlReplacement,f=void 0===b.refresh?!1:b.refresh,g=void 0===b.token?void 0:b.token,h=void 0===b.xssiPrefix?void 0:b.xssiPrefix;L(c.getAttribute("src"),c);var n=R(a.win,"batched-xhr");return va(c,d,f).then(function(a){void 0!==g&&(a.fetchOpt.method="POST",a.fetchOpt.headers={"Content-Type":"application/x-www-form-urlencoded"},a.fetchOpt.body={ampViewerAuthToken:g});return n.fetchJson(a.xhrUrl,a.fetchOpt)}).then(function(b){return R(a.win,
"xhr").xssiJson(b,h)}).then(function(a){if(null==a)throw Error("Response is undefined.");var b=e||".";if("."==b)b=a;else{b=b.split(".");for(var c=0;c<b.length;c++){var d=b[c];if(d&&a&&void 0!==a[d]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,d)))a=a[d];else{a=void 0;break}}b=a}return b}).catch(function(a){throw D().createError("failed fetching JSON data",a);})}
function va(a,c,b){var e=a.getAttribute("src"),d=ra(a);return(1<=c?d.expandUrlAsync(e):Promise.resolve(e)).then(function(e){if(1==c){var g=d.collectUnwhitelistedVarsSync(a);if(0<g.length)throw D().createError('URL variable substitutions in CORS fetches from dynamic URLs (e.g. via amp-bind) require opt-in. Please add data-amp-replace="'+(g.join(" ")+'" to the <')+(a.tagName+"> element. See https://bit.ly/amp-var-subs."));}var f={};a.hasAttribute("credentials")&&(f.credentials=a.getAttribute("credentials"));
b&&(f.cache="reload");return{xhrUrl:e,fetchOpt:f}})};var S;function wa(a,c){var b=void 0,e=a,d=c;var f=function(a){try{return d(a)}catch(k){throw self.__AMP_REPORT_ERROR(k),k;}};var g=xa(),h=!1;b&&(h=b.capture);e.addEventListener("message",f,g?b:h);return function(){e&&e.removeEventListener("message",f,g?b:h);f=e=d=null}}function xa(){if(void 0!==S)return S;S=!1;try{var a={get capture(){S=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(c){}return S};function ya(a){for(var c=a.nodeName,b=0,e=0,d=a.previousElementSibling;d&&25>e&&100>b;)d.nodeName==c&&e++,b++,d=d.previousElementSibling;return 25>e&&100>b?"."+e:""};var T,za="Webkit webkit Moz moz ms O o".split(" ");function Aa(a){var c;var b=a.style;if(H("border","--"))b="border";else{T||(T=Object.create(null));var e=T.border;if(!e){e="border";if(void 0===b.border){var d;b:{for(d=0;d<za.length;d++){var f=za[d]+"Border";if(void 0!==b[f]){d=f;break b}}d=""}void 0!==b[d]&&(e=d)}T.border=e}b=e}if(b){var g=c?"none"+c:"none";H(b,"--")?a.style.setProperty(b,g):a.style[b]=g}};function Ba(a){a=parseFloat(a);return x(a)?a:void 0};var U={};
function Ca(a,c,b){F("bodymovinanimation","Attribute type required for <amp-ad>: %s",c);var e=0;for(var d=a;d&&d!=d.parent;d=d.parent)e++;e=String(e)+"-"+Da(a);var f=d={},g=c.dataset,h;for(h in g)H(h,"vars")||(f[h]=g[h]);if(h=c.getAttribute("json")){try{var n=JSON.parse(h)}catch(Oa){n=null}if(void 0===n)throw D().createError("Error parsing JSON in json attribute in element %s",c);for(var k in n)f[k]=n[k]}k=d;n=Date.now();d=c.getAttribute("width");f=c.getAttribute("height");k=k?k:{};k.width=Ba(d);
k.height=Ba(f);c.getAttribute("title")&&(k.title=c.getAttribute("title"));var B=a.location.href;"about:srcdoc"==B&&(B=a.parent.location.href);var Z=Q(c),C=ta(c,"documentInfo").get();d=ta(c,"viewer").getUnconfirmedReferrerUrl();var q=c.getPageLayoutBox();f=k;h=z.thirdParty+"/2005050322002/ampcontext-v0.js";g=C.sourceUrl;var Ga=C.canonicalUrl;C=C.pageViewId;B={href:B};var Ha=c.tagName,Ia={localDev:!1,development:w().development,esm:!1,minified:!0,lite:w().lite,test:!1,log:w().log,version:w().version,
rtvVersion:w().rtvVersion,singlePassType:w().singlePassType},Ja=!(!a.AMP_CONFIG||!a.AMP_CONFIG.canary);Z=!Z.isVisible();q=q?{left:q.left,top:q.top,width:q.width,height:q.height}:null;var Ka=c.getIntersectionChangeEntry();var p=c;for(var O=[],u=0;p&&1==p.nodeType&&25>u;){var v="";p.id&&(v="/"+p.id);var La=p.nodeName.toLowerCase();O.push(""+La+v+ya(p));u++;p=p.parentElement}p=O.join();O=p.length;u=5381;for(v=0;v<O;v++)u=33*u^p.charCodeAt(v);f._context=G({ampcontextVersion:"2005050322002",ampcontextFilepath:h,
sourceUrl:g,referrer:d,canonicalUrl:Ga,pageViewId:C,location:B,startTime:n,tagName:Ha,mode:Ia,canary:Ja,hidden:Z,initialLayoutRect:q,initialIntersection:Ka,domFingerprint:String(u>>>0),experimentToggles:oa(a),sentinel:e});(a=c.getAttribute("src"))&&(k.src=a);d=k;d.type="bodymovinanimation";Object.assign(d._context,b);return d}
function Ea(a,c,b){var e={},d=e.disallowCustom,f=e.allowFullscreen;b=Ca(a,c,b);var g=a.document.createElement("iframe");U[b.type]||(U[b.type]=0);U[b.type]+=1;e=c.getAmpDoc();a=Fa(a,e,d);var h=K(a).hostname;e=JSON.stringify(G({host:h,type:b.type,count:U[b.type],attributes:b}));g.src=a;g.ampLocation=K(a);g.name=e;b.width&&(g.width=b.width);b.height&&(g.height=b.height);b.title&&(g.title=b.title);f&&g.setAttribute("allowfullscreen","true");g.setAttribute("scrolling","no");Aa(g);g.onload=function(){this.readyState=
"complete"};g.setAttribute("allow","sync-xhr 'none';");var n=["facebook"];n.includes("bodymovinanimation")||Ma(g);g.setAttribute("data-amp-3p-sentinel",b._context.sentinel);return g}
function Fa(a,c,b){var e=void 0;if(b)b=null;else if(b=e,c=c.getMetaByName("amp-3p-iframe-src")){var d=L(c,'meta[name="amp-3p-iframe-src"]');F(-1==d.indexOf("?"),"3p iframe url must not include query string %s in element %s.",d,c);var f=K(d);F("localhost"==f.hostname&&!b||f.origin!=K(a.location.href).origin,"3p iframe url must not be on the same origin as the current document %s (%s) in element %s. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.",d,
f.origin,c);b=d+"?2005050322002"}else b=null;var g=b;(b=g)||(a.__AMP_DEFAULT_BOOTSTRAP_SUBDOMAIN=a.__AMP_DEFAULT_BOOTSTRAP_SUBDOMAIN||"d-"+Da(a),b="https://"+a.__AMP_DEFAULT_BOOTSTRAP_SUBDOMAIN+("."+z.thirdPartyFrameHost+"/2005050322002/frame.html"));return b}function Da(a){if(a.crypto&&a.crypto.getRandomValues){var c=new Uint32Array(2);a.crypto.getRandomValues(c);var b=String(c[0])+c[1]}else b=String(a.Math.random()).substr(2)+"0";return b}
function Ma(a){if(a.sandbox&&a.sandbox.supports){for(var c=["allow-top-navigation-by-user-activation","allow-popups-to-escape-sandbox"],b="allow-forms allow-modals allow-pointer-lock allow-popups allow-same-origin allow-scripts".split(" "),e=0;e<c.length;e++){var d=c[e];if(!a.sandbox.supports(d)){E().info("3p-frame","Iframe doesn't support %s",d);return}}a.sandbox=c.join(" ")+" "+b.join(" ")}};function V(a){a=AMP.BaseElement.call(this,a)||this;a.F=Q(a.element);a.h=null;a.D=null;a.w=null;a.C=null;a.l=null;a.o=null;a.B=null;return a}var W=AMP.BaseElement;V.prototype=aa(W.prototype);V.prototype.constructor=V;if(da)da(V,W);else for(var X in W)if("prototype"!=X)if(Object.defineProperties){var Na=Object.getOwnPropertyDescriptor(W,X);Na&&Object.defineProperty(V,X,Na)}else V[X]=W[X];V.I=W.prototype;
V.prototype.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};
V.prototype.preconnectCallback=function(a){var c=R(this.win,"preconnect"),b="svg"===this.w?"https://cdnjs.cloudflare.com/ajax/libs/bodymovin/4.13.0/bodymovin_light.min.js":"https://cdnjs.cloudflare.com/ajax/libs/bodymovin/4.13.0/bodymovin.min.js",e=this.getAmpDoc(),d=Fa(this.win,e,void 0);c.preload(e,d,"document");c.preload(e,z.thirdParty+"/2005050322002/f.js","script");c.url(this.getAmpDoc(),b,a)};
V.prototype.buildCallback=function(){var a=this;this.D=this.element.getAttribute("loop")||"true";this.C=!this.element.hasAttribute("noautoplay");this.w=this.element.getAttribute("renderer")||"svg";F(this.element.hasAttribute("src"),"The src attribute must be specified for <amp-bodymovin-animation>");L(this.element.getAttribute("src"),this.element);var c=new ka;this.l=c.promise;this.o=c.resolve;this.registerAction("play",function(){Y(a,"play")},1);this.registerAction("pause",function(){Y(a,"pause")},
1);this.registerAction("stop",function(){Y(a,"stop")},1);this.registerAction("seekTo",function(b){var c=b.args;if(c){var d=parseFloat(c&&c.time);x(d)&&Y(a,"seekTo","time",d);c=parseFloat(c&&c.percent);x(c)&&Y(a,"seekTo","percent",Math.min(Math.max(c,0),1))}},1)};
V.prototype.layoutCallback=function(){var a=this,c=ua(this.F,this.element);return c.then(function(b){var c=Ea(a.win,a.element,{loop:a.D,autoplay:a.C,renderer:a.w,animationData:b});return R(a.win,"vsync").mutatePromise(function(){a.applyFillContent(c);var b=a.H.bind(a);b=wa(a.win,b);a.B=b;a.element.appendChild(c);a.h=c}).then(function(){return a.l})})};
V.prototype.unlayoutCallback=function(){if(this.h){var a=this.h;a.parentElement&&a.parentElement.removeChild(a);this.h=null}this.B&&this.B();a=new ka;this.l=a.promise;this.o=a.resolve;return!0};V.prototype.H=function(a){if((!this.h||a.source==this.h.contentWindow)&&a.data&&("[object Object]"===ha.call(a.data)||H(a.data,"{"))){var c="[object Object]"===ha.call(a.data)?a.data:JSON.parse(a.data);void 0!==c&&"ready"==c.action&&this.o()}};
function Y(a,c,b,e){a.l.then(function(){if(a.h&&a.h.contentWindow){var d=JSON.stringify(G({action:c,valueType:b||"",value:e||""}));a.h.contentWindow.postMessage(d,"*")}})}(function(a){a.registerElement("amp-bodymovin-animation",V)})(self.AMP);
})});

//# sourceMappingURL=amp-bodymovin-animation-0.1.js.map
